/* AUTO-GENERATED by scripts/generate-mock-zones.ts — DO NOT EDIT BY HAND.
 *
 * Source of truth: data/zones.geojson (P4's verified Delhi zone dataset).
 * Static attributes (depressionDepthM, drainageDeficit, historyScore,
 * criticalRainMmHr) are REAL data from P4 (see data/SOURCES.md).
 * Baseline live-weather values are a documented SIMULATION snapshot used by the
 * client-side rainfall simulator; the UI shows a SIMULATION badge whenever it runs.
 * Regenerate with: npx tsx scripts/generate-mock-zones.ts
 */
import type { ZoneStatic, LiveInputs } from "@aquashield/risk-core";

export type SeedEntry = {
  statics: ZoneStatic;
  baseline: Omit<LiveInputs, "rainNowMmHr">;
  baselineRainMmHr: number;
};

export const SEEDS: Record<string, SeedEntry> = {
  "z_minto": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 4.8,
      drainageDeficit: 82,
      historyScore: 88,
      criticalRainMmHr: 35,
    },
    baseline: { rain24hMm: 70, reportTrusts: [0.86, 0.8] },
    baselineRainMmHr: 55,
  },
  "z_prahladpur": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 3.9,
      drainageDeficit: 68,
      historyScore: 71,
      criticalRainMmHr: 40,
    },
    baseline: { rain24hMm: 45, reportTrusts: [0.75, 0.6] },
    baselineRainMmHr: 44,
  },
  "z_zakhira": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 3.2,
      drainageDeficit: 55,
      historyScore: 62,
      criticalRainMmHr: 42,
    },
    baseline: { rain24hMm: 8, reportTrusts: [] },
    baselineRainMmHr: 5,
  },
  "z_ito": {
    statics: {
      isUnderpass: false,
      depressionDepthM: 1.5,
      drainageDeficit: 45,
      historyScore: 55,
      criticalRainMmHr: 55,
    },
    baseline: { rain24hMm: 45, reportTrusts: [] },
    baselineRainMmHr: 31,
  },
  "z_isbt_kashmere_gate": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 5.2,
      drainageDeficit: 85,
      historyScore: 92,
      criticalRainMmHr: 30,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_nd_railway": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 4.1,
      drainageDeficit: 78,
      historyScore: 80,
      criticalRainMmHr: 35,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_azad_market": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 3.6,
      drainageDeficit: 72,
      historyScore: 74,
      criticalRainMmHr: 38,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_pandav_nagar": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 3,
      drainageDeficit: 65,
      historyScore: 60,
      criticalRainMmHr: 40,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_rajinder_nagar": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 2.8,
      drainageDeficit: 60,
      historyScore: 58,
      criticalRainMmHr: 42,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_mayur_vihar": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 3.4,
      drainageDeficit: 70,
      historyScore: 65,
      criticalRainMmHr: 38,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_seelampur": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 4,
      drainageDeficit: 76,
      historyScore: 75,
      criticalRainMmHr: 35,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_shakur_basti": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 2.5,
      drainageDeficit: 50,
      historyScore: 35,
      criticalRainMmHr: 45,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_mundka": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 2.2,
      drainageDeficit: 48,
      historyScore: 40,
      criticalRainMmHr: 48,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_pitampura": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 2,
      drainageDeficit: 42,
      historyScore: 38,
      criticalRainMmHr: 50,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
  "z_model_town": {
    statics: {
      isUnderpass: true,
      depressionDepthM: 2.3,
      drainageDeficit: 44,
      historyScore: 42,
      criticalRainMmHr: 48,
    },
    baseline: { rain24hMm: 55, reportTrusts: [] },
    baselineRainMmHr: 35,
  },
};

/** Fallback for zones missing from the real dataset. */
export const DEFAULT_SEED: SeedEntry = {
  statics: { isUnderpass: false, depressionDepthM: 1.5, drainageDeficit: 50, historyScore: 40, criticalRainMmHr: 50 },
  baseline: { rain24hMm: 55, reportTrusts: [] },
  baselineRainMmHr: 35,
};
