/**
 * scripts/generate-mock-zones.ts
 * ==============================
 * Regenerates mock data + the frontend simulator seed table from P4's REAL zone
 * dataset (data/zones.geojson), so there is one source of truth:
 *
 *   1. mocks/zones.json            — ZoneListResponse (15 real Delhi zones)
 *   2. mocks/zone-detail.json      — ZoneDetail for z_minto (engine-consistent)
 *   3. apps/web/lib/zoneStaticData.ts — AUTO-GENERATED seed table for the browser
 *
 * All risk/tier/etaMin values are computed by `@aquashield/risk-core` (never typed
 * by hand) using each zone's real static attributes and a DOCUMENTED snapshot
 * scenario (see SNAPSHOT_TS / FORECAST_RAMP below).
 *
 * Usage:  npx tsx scripts/generate-mock-zones.ts
 * Then:   npm run validate:mocks   (must pass)
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { computeRisk, computeEta } from "../packages/risk-core/src/index";
import type { ZoneStatic, LiveInputs } from "../packages/risk-core/src/index";
import { ZoneListResponseSchema, ZoneDetailSchema } from "../packages/types/src/index";

const ROOT = join(__dirname, "..");

// ---------- snapshot scenario (documented, reproducible) ----------
/** Fixed snapshot time so regeneration is deterministic (stable git diffs). */
const SNAPSHOT_TS = "2026-10-10T12:00:00.000Z";
/** Forecast scenario for etaMin: rain ramps +35 mm/h over the next 3h (15-min steps). */
const FORECAST_RAMP_DELTA = 35;
/** Default live-baseline for zones without a hand-calibrated baseline. */
const DEFAULT_BASELINE = { rain24hMm: 55, reportTrusts: [] as number[], baselineRainMmHr: 35 };

/** Hand-calibrated baselines for the 4 original live zones (kept: they reproduce the
 *  storm snapshot the live API originally returned). Real statics override everything else. */
const CALIBRATED_BASELINES: Record<string, { rain24hMm: number; reportTrusts: number[]; baselineRainMmHr: number }> = {
  z_minto: { rain24hMm: 70, reportTrusts: [0.86, 0.8], baselineRainMmHr: 55 },
  z_prahladpur: { rain24hMm: 45, reportTrusts: [0.75, 0.6], baselineRainMmHr: 44 },
  z_ito: { rain24hMm: 45, reportTrusts: [], baselineRainMmHr: 31 },
  z_zakhira: { rain24hMm: 8, reportTrusts: [], baselineRainMmHr: 5 },
};

type GeoFeature = {
  properties: {
    id: string;
    name: string;
    lat: number;
    lng: number;
    isUnderpass: boolean;
    depressionDepthM: number;
    drainageDeficit: number;
    historyScore: number;
    criticalRainMmHr: number;
  };
};

// ---------- load real dataset ----------
const geo = JSON.parse(readFileSync(join(ROOT, "data", "zones.geojson"), "utf8"));
const features: GeoFeature[] = geo.features;
if (!Array.isArray(features) || features.length === 0) {
  console.error("ERROR: data/zones.geojson has no features");
  process.exit(1);
}

const staticsOf = (p: GeoFeature["properties"]): ZoneStatic => ({
  isUnderpass: p.isUnderpass,
  depressionDepthM: p.depressionDepthM,
  drainageDeficit: p.drainageDeficit,
  historyScore: p.historyScore,
  criticalRainMmHr: p.criticalRainMmHr,
});

const baselineOf = (id: string) => CALIBRATED_BASELINES[id] ?? DEFAULT_BASELINE;

const liveOf = (id: string): LiveInputs => {
  const b = baselineOf(id);
  return { rainNowMmHr: b.baselineRainMmHr, rain24hMm: b.rain24hMm, reportTrusts: b.reportTrusts };
};

const forecastRamp = (startMmHr: number) =>
  Array.from({ length: 13 }, (_, i) => ({
    ts: new Date(Date.parse(SNAPSHOT_TS) + i * 15 * 60_000).toISOString(),
    mmHr: Math.round((startMmHr + (FORECAST_RAMP_DELTA * i) / 12) * 10) / 10,
  }));

// ---------- 1. mocks/zones.json ----------
const zones = features.map((f) => {
  const p = f.properties;
  const b = baselineOf(p.id);
  const statics = staticsOf(p);
  const breakdown = computeRisk(statics, liveOf(p.id), computeEta(statics, liveOf(p.id), forecastRamp(b.baselineRainMmHr), Date.parse(SNAPSHOT_TS)));
  return {
    id: p.id,
    name: p.name,
    lat: p.lat,
    lng: p.lng,
    isUnderpass: p.isUnderpass,
    risk: breakdown.risk,
    tier: breakdown.tier,
    etaMin: breakdown.etaMin,
    updatedAt: SNAPSHOT_TS,
    stale: false,
  };
});

const zonesDoc = {
  _note: "SIMULATION snapshot generated by scripts/generate-mock-zones.ts from data/zones.geojson (P4). Risk/eta computed by @aquashield/risk-core — not hand-typed. Live API data is authoritative when USE_MOCKS=false.",
  zones,
};

// ---------- 2. mocks/zone-detail.json ----------
const minto = features.find((f) => f.properties.id === "z_minto")!;
const mintoStatics = staticsOf(minto.properties);
const mintoLive = liveOf("z_minto");
const mintoForecast = forecastRamp(baselineOf("z_minto").baselineRainMmHr);
const mintoBreakdown = computeRisk(
  mintoStatics,
  mintoLive,
  computeEta(mintoStatics, mintoLive, mintoForecast, Date.parse(SNAPSHOT_TS)),
);
const mintoSummary = zones.find((z) => z.id === "z_minto")!;

const prevDetailPath = join(ROOT, "mocks", "zone-detail.json");
const prevReports = existsSync(prevDetailPath)
  ? JSON.parse(readFileSync(prevDetailPath, "utf8")).reports ?? []
  : [];

const detailDoc = {
  _note: zonesDoc._note,
  zone: mintoSummary,
  breakdown: mintoBreakdown,
  rain: { nowMmHr: baselineOf("z_minto").baselineRainMmHr, last24hMm: baselineOf("z_minto").rain24hMm },
  forecast: mintoForecast,
  reports: prevReports,
};

// ---------- validate before writing ----------
ZoneListResponseSchema.parse(zonesDoc);
ZoneDetailSchema.parse(detailDoc);

// ---------- 3. apps/web/lib/zoneStaticData.ts (generated seed table) ----------
const seedLines = features.map((f) => {
  const p = f.properties;
  const b = baselineOf(p.id);
  return `  ${JSON.stringify(p.id)}: {
    statics: {
      isUnderpass: ${p.isUnderpass},
      depressionDepthM: ${p.depressionDepthM},
      drainageDeficit: ${p.drainageDeficit},
      historyScore: ${p.historyScore},
      criticalRainMmHr: ${p.criticalRainMmHr},
    },
    baseline: { rain24hMm: ${b.rain24hMm}, reportTrusts: [${b.reportTrusts.join(", ")}] },
    baselineRainMmHr: ${b.baselineRainMmHr},
  },`;
});

const zoneStaticData = `/* AUTO-GENERATED by scripts/generate-mock-zones.ts — DO NOT EDIT BY HAND.
 *
 * Source of truth: data/zones.geojson (P4's verified Delhi zone dataset).
 * Static attributes (depressionDepthM, drainageDeficit, historyScore,
 * criticalRainMmHr) are REAL data from P4 (see data/SOURCES.md).
 * Baseline live-weather values are a documented SIMULATION snapshot used by the
 * client-side rainfall simulator; the UI shows a SIMULATION badge whenever it runs.
 * Regenerate with: npx tsx scripts/generate-mock-zones.ts
 */
import type { ZoneStatic, LiveInputs } from "@aquashield/risk-core";

export type SeedEntry = {
  statics: ZoneStatic;
  baseline: Omit<LiveInputs, "rainNowMmHr">;
  baselineRainMmHr: number;
};

export const SEEDS: Record<string, SeedEntry> = {
${seedLines.join("\n")}
};

/** Fallback for zones missing from the real dataset. */
export const DEFAULT_SEED: SeedEntry = {
  statics: { isUnderpass: false, depressionDepthM: 1.5, drainageDeficit: 50, historyScore: 40, criticalRainMmHr: 50 },
  baseline: { rain24hMm: ${DEFAULT_BASELINE.rain24hMm}, reportTrusts: [] },
  baselineRainMmHr: ${DEFAULT_BASELINE.baselineRainMmHr},
};
`;

// ---------- write ----------
writeFileSync(join(ROOT, "mocks", "zones.json"), JSON.stringify(zonesDoc, null, 2) + "\n");
writeFileSync(prevDetailPath, JSON.stringify(detailDoc, null, 2) + "\n");
writeFileSync(join(ROOT, "apps", "web", "lib", "zoneStaticData.ts"), zoneStaticData);

console.log(`✓ mocks/zones.json         — ${zones.length} real zones, risk computed by risk-core`);
console.log(`✓ mocks/zone-detail.json   — z_minto risk ${mintoBreakdown.risk} (${mintoBreakdown.tier}), ${mintoForecast.length} forecast pts`);
console.log(`✓ apps/web/lib/zoneStaticData.ts — ${features.length} generated seeds`);
console.log(`snapshot=${SNAPSHOT_TS} scenario=rain+${FORECAST_RAMP_DELTA}mm/h over 3h`);
