/**
 * INSTALL HOOKS — run once after `npm install`
 * Sets up the pre-push hook so every `git push` is automatically validated.
 * 
 * Run: npx tsx scripts/install-hooks.ts
 */
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const hooksDir = join(root, ".git", "hooks");
const hookFile = join(hooksDir, "pre-push");

// Ensure .git/hooks exists
if (!existsSync(hooksDir)) {
  mkdirSync(hooksDir, { recursive: true });
}

const hookContent = `#!/usr/bin/env sh
# DO NOT EDIT — auto-generated by scripts/install-hooks.ts
# To re-run: npx tsx scripts/install-hooks.ts

echo ""
echo "Running pre-push checks..."
node --import tsx scripts/pre-push-check.ts
`;

writeFileSync(hookFile, hookContent, "utf8");

// Make it executable on Unix (no-op on Windows but harmless)
try {
  execSync("chmod +x " + hookFile, { stdio: "ignore" });
} catch { /* Windows */ }

console.log("  pre-push hook installed at .git/hooks/pre-push");
console.log("  Every \\`git push\\` will now validate mocks, tests, and types first.");
console.log("  To bypass (emergency only): git push --no-verify");
